// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyChiTieu.Data;

#nullable disable

namespace QuanLyChiTieu.Migrations
{
    [DbContext(typeof(ChiTieuDbContext))]
    [Migration("20260716161031_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyChiTieu.Models.ChiTietChiaTien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KhoanChiId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<decimal>("TyLe")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("KhoanChiId", "NguoiDungId")
                        .IsUnique();

                    b.ToTable("ChiTietChiaTien");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DanhMuc");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenDanhMuc = "Ăn uống"
                        },
                        new
                        {
                            Id = 2,
                            TenDanhMuc = "Điện nước"
                        },
                        new
                        {
                            Id = 3,
                            TenDanhMuc = "Đồ dùng chung"
                        },
                        new
                        {
                            Id = 4,
                            TenDanhMuc = "Khác"
                        });
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.KhoanChi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnhPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayMua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiTraId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenMatHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucId");

                    b.HasIndex("NguoiTraId");

                    b.ToTable("KhoanChi");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NguoiDung");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DangHoatDong = true,
                            NgayThamGia = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ten = "Người 1"
                        },
                        new
                        {
                            Id = 2,
                            DangHoatDong = true,
                            NgayThamGia = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ten = "Người 2"
                        },
                        new
                        {
                            Id = 3,
                            DangHoatDong = true,
                            NgayThamGia = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ten = "Người 3"
                        });
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.ChiTietChiaTien", b =>
                {
                    b.HasOne("QuanLyChiTieu.Models.KhoanChi", "KhoanChi")
                        .WithMany("ChiTietChia")
                        .HasForeignKey("KhoanChiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyChiTieu.Models.NguoiDung", "NguoiDung")
                        .WithMany("PhanChiaCuaToi")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoanChi");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.KhoanChi", b =>
                {
                    b.HasOne("QuanLyChiTieu.Models.DanhMuc", "DanhMuc")
                        .WithMany()
                        .HasForeignKey("DanhMucId");

                    b.HasOne("QuanLyChiTieu.Models.NguoiDung", "NguoiTra")
                        .WithMany("KhoanChiDaTra")
                        .HasForeignKey("NguoiTraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("NguoiTra");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.KhoanChi", b =>
                {
                    b.Navigation("ChiTietChia");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.NguoiDung", b =>
                {
                    b.Navigation("KhoanChiDaTra");

                    b.Navigation("PhanChiaCuaToi");
                });
#pragma warning restore 612, 618
        }
    }
}
